### ISSUE TITLE
file.php relying on WP functions

### ISSUE THREAD

**Issue by pdechery** [iamntz/carbon-fields-urlpicker#14]
This package has a file (file.php) which is being [autoloaded](https://github.com/iamntz/carbon-fields-urlpicker/blob/3ef6d0757dc31b143d1b2b802a98d9fafb4207eb/composer.json#L17). 

This causes issues with setups that run composer's autoload before WP's actions are booted. [Bedrock](https://roots.io/bedrock/)'s an example, as mentioned [here](https://github.com/htmlburger/carbon-fields/pull/115), but in my particular case I'm not even using Bedrock. 

I just need to run composer's autoload in `wp-config.php` in order to use another package there. And I'm getting fatal errors. 

I'd sort of solved the problem commenting all the code in `file.php` and pasting it in my `functions.php`. My site so far seems to be running well. 

Is there any hope that will be changed in any future release?

Thank you

**Comment by iamntz** [comment]
Hey @pdechery Unfortunately I'm not familiar with Bedrock, but it seems that it tries to convert WP to something that it is not.

For your particular case, you may have two options:

- move code out of wp-config to a `mu-plugin`. Within `mu-plugin`s you have access to low-level WP core, so that may be useful;
- keep _two_ `composer.json` files, one for root, the other one as a plugin.
